const keywordLists = {
  coding: [
    "program",
    "virus",
    "MERN",
    "intern",
    "software",
    "developer",
    "algorithm",
    "debug",
    "Python",
    "JavaScript",
    "C++",
    "Java",
    "Ruby",
    "HTML",
    "CSS",
    "React",
    "Node.js",
    "API",
    "REST",
    "Angular",
    "Vue",
    "Django",
    "Flask",
    "TypeScript",
    "Git",
    "version control",
    "SQL",
    "NoSQL",
    "database",
    "server",
    "cloud",
    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "machine learning",
    "AI",
    "Deep learning",
    "TensorFlow",
    "PyTorch",
    "ML",
    "data science",
    "analytics",
    "Big Data",
    "Hadoop",
    "Spark",
    "GraphQL",
    "WebSocket",
    "OAuth",
    "JWT",
    "authentication",
    "authorization",
    "Microservices",
    "DevOps",
    "containerization",
    "cloud computing",
    "serverless",
    "API Gateway",
    "message broker",
    "RESTful",
    "SOAP",
    "data structure",
    "algorithm design",
    "testing",
    "TDD",
    "BDD",
    "agile",
    "scrum",
    "Kanban",
    "continuous integration",
    "continuous deployment",
    "code review",
    "refactoring",
    "software architecture",
    "design pattern",
    "UML",
    "OOP",
    "functional programming",
    "imperative programming",
    "compiler",
    "interpreter",
    "scripting",
    "automation",
    "DevSecOps",
    "security",
    "penetration testing",
    "ethical hacking",
    "cybersecurity",
    "cryptography",
    "blockchain",
  ],
  music: [
    "song",
    "album",
    "artist",
    "band",
    "concert",
    "music",
    "guitar",
    "piano",
    "drums",
    "singer",
    "composer",
    "producer",
    "DJ",
    "electronic",
    "pop",
    "rock",
    "jazz",
    "classical",
    "blues",
    "folk",
    "hip hop",
    "rap",
    "country",
    "reggae",
    "R&B",
    "soul",
    "opera",
    "symphony",
    "orchestra",
    "lyrics",
    "melody",
    "harmony",
    "beat",
    "rhythm",
    "soundtrack",
    "instrumental",
    "vocals",
    "chorus",
    "solo",
    "cover",
    "remix",
    "live performance",
    "music video",
    "music festival",
    "album release",
    "singing",
    "music theory",
    "composition",
    "arrangement",
    "improvisation",
    "music production",
    "audio engineering",
    "recording",
    "mixing",
    "mastering",
    "sound design",
    "studio",
    "band practice",
    "jamming",
    "musician",
    "music industry",
    "record label",
    "music charts",
    "top hits",
    "billboard",
    "streaming",
    "playlist",
    "radio",
    "music app",
    "soundcloud",
    "spotify",
    "apple music",
    "youtube music",
    "music genre",
    "musical",
    "acoustic",
    "electro",
    "dance",
    "EDM",
    "ambient",
    "chill",
    "trance",
    "techno",
    "house",
    "dubstep",
    "grunge",
    "alternative",
    "metal",
    "hardcore",
    "indie",
    "punk",
    "ska",
    "country",
    "bluegrass",
    "gospel",
    "samba",
    "bossa nova",
    "latin",
    "flamenco",
  ],
  dance: [
    "choreography",
    "ballet",
    "hip-hop",
    "dance",
    "performance",
    "salsa",
    "tango",
    "jazz",
    "modern dance",
    "contemporary",
    "tap dance",
    "ballroom",
    "street dance",
    "breakdance",
    "dance battle",
    "dance class",
    "dance studio",
    "dance rehearsal",
    "dance routine",
    "dance competition",
    "dance festival",
    "dance troupe",
    "dance group",
    "solo dance",
    "partner dance",
    "couple dance",
    "group dance",
    "dance teacher",
    "dance instructor",
    "dance workshop",
    "dance choreography",
    "dance moves",
    "dance steps",
    "dance style",
    "dance technique",
    "dance performance",
    "dance rehearsal",
    "dance training",
    "dance workout",
    "dance exercise",
    "dance cardio",
    "dance fitness",
    "dance practice",
    "dance video",
    "dance tutorial",
    "dance lesson",
    "dance class",
    "dance party",
    "dance event",
    "dance show",
    "dance theater",
    "dance production",
    "dance company",
    "dance ensemble",
    "dance director",
    "dance producer",
    "dance notation",
    "dance terminology",
    "dance history",
    "dance culture",
    "dance traditions",
    "dance fashion",
    "dance costumes",
    "dance makeup",
    "dance stage",
    "dance lighting",
    "dance sound",
    "dance music",
    "dance rhythm",
    "dance beat",
    "dance floor",
    "dance competition",
    "dance contest",
    "dance awards",
    "dance judges",
    "dance scoring",
    "dance routine",
    "dance formation",
    "dance coordination",
    "dance expression",
    "dance improvisation",
    "dance freestyle",
    "dance fusion",
    "dance trends",
    "dance challenges",
    "dance memes",
    "dance videos",
    "dance clips",
    "dance auditions",
    "dance casting",
    "dance agencies",
    "dance industry",
    "dance career",
    "dance profession",
    "dance education",
    "dance schools",
    "dance programs",
    "dance scholarships",
  ],
  sports: [
    "football",
    "basketball",
    "soccer",
    "athlete",
    "sports",
    "game",
    "match",
    "team",
    "coach",
    "training",
    "fitness",
    "exercise",
    "workout",
    "gym",
    "boxing",
    "wrestling",
    "baseball",
    "hockey",
    "tennis",
    "golf",
    "cricket",
    "rugby",
    "volleyball",
    "swimming",
    "running",
    "cycling",
    "track",
    "field",
    "marathon",
    "triathlon",
    "endurance",
    "strength",
    "conditioning",
    "sportswear",
    "equipment",
    "gear",
    "score",
    "tournament",
    "league",
    "championship",
    "medal",
    "trophy",
    "award",
    "record",
    "performance",
    "strategy",
    "tactics",
    "skill",
    "technique",
    "referee",
    "umpire",
    "official",
    "stadium",
    "arena",
    "field",
    "court",
    "gymnasium",
    "pool",
    "track and field",
    "sports medicine",
    "sports science",
    "sports psychology",
    "sports nutrition",
    "sports therapy",
    "rehabilitation",
    "injury",
    "prevention",
    "recovery",
    "athletic training",
    "personal trainer",
    "sports coach",
    "sports management",
    "sports marketing",
    "sports broadcasting",
    "sports journalism",
    "sports commentary",
    "sports analysis",
    "sports statistics",
    "sports data",
    "fantasy sports",
    "eSports",
    "sports betting",
    "sports gambling",
    "sports fan",
    "sports culture",
    "sports history",
    "sports trivia",
    "sports events",
    "sports news",
    "sports updates",
  ],
};

function filterVideos(keywords) {
  const videos = document.querySelectorAll("#video-title");

  videos.forEach((video) => {
    const title = video.textContent.toLowerCase();
    const shouldBlur = !keywords.some((keyword) => title.includes(keyword));

    if (shouldBlur) {
      video.closest("ytd-rich-item-renderer").style.filter = "blur(10px)";
    } else {
      video.closest("ytd-rich-item-renderer").style.filter = ""; // Ensure relevant videos are not blurred
    }
  });
}

// Retrieve the keyword and category from storage and apply the filter
chrome.storage.local.get(["keyword", "category"], (data) => {
  const keyword = data.keyword ? data.keyword.toLowerCase() : "";
  const category = data.category ? data.category.toLowerCase() : "";

  if (category && keywordLists[category]) {
    const keywords = keywordLists[category].concat(keyword); // Add user-provided keyword to the list

    filterVideos(keywords);

    // Set up a MutationObserver to watch for new videos being loaded
    const observer = new MutationObserver(() => {
      filterVideos(keywords);
    });

    // Observe the entire document body for changes
    observer.observe(document.body, { childList: true, subtree: true });
  }
});
